### PR TITLE
Integrate Clair for analyzing image vulnerability

### LINKED ISSUE #914: Proposal: Integrate Clair for analyzing image vulnerability
[Clair](https://github.com/coreos/clair) is a tool to analyze the vulnerabilities of docker images. It gets the vulnerabilities of the image by analyzing the features and their vulnerabilities added by each layer. In Harbor, each layer of the images can be sent to Clair server to analyze when they are pushed, and show their vulnerabilities in the UI.

There are two ways to integrate Clair:
- Configurable Clair server url
  If the Clair server url is configured, each layer will be analyzed when the image is pushed, otherwise will has no vulnerability analysis. 
- Clair as component of Harbor
  Integrate Clair as component of Harbor, and start it with Harbor by docker-compose. As the Clair server need to track an upstream vulnerability database and imports them into Clair, so the deployment machine should be able to connect to the Internet.

WorkItems:
- [x] Read Clair server url from config
- [x] Analyse image when receive notification of pushing images
- [x] Get vulnerabilities when view image details
- [ ] Show vulnerabilities in UI (Not familiar with AngularJS, need help)
- [ ] Test and add test cases

### PR DESCRIPTION
**Pull request by supereagle**
fix #914

This PR just finishes the backend work, the frontend work to show the image security will be in another PR.

@reasonerjt PTAL.

### CODE REVIEW

**Comment by rikatz** [comment]
@supereagle Have you seen this? https://travis-ci.org/vmware/harbor/builds/185603091#L550

**Comment by supereagle** [comment]
@rikatz   Yes. I will fix this.

**Comment by rikatz** [comment]
How is this going? Really need this feature :) 

@supereagle May I help you with something?

**Comment by supereagle** [comment]
@reasonerjt  What about the plan of this integration?  Any comments about this draft implementation?

@rikatz  Thanks, I will happily ping you if need any help. Now I am not sure about the detail plan, and looking forward to the confirmation.

**Comment by damelo** [comment]
@supereagle, any news about this feature?  i'm looking forward to it. I can help if u need so.

**Comment by reasonerjt** [comment]
Will rework the clair integration, closing the issue.

**Comment by supereagle** [comment]
@reasonerjt  Any detail plan about the integration?

**Pull request closed without merging**
