### PR TITLE
Add repo into DB, update code per comments

### PR DESCRIPTION
**Pull request by wy65701436**
1, update code per comments.
2, add retry to init registry client.
3, re-factor diffRepo() 
4, add testing code.

### CODE REVIEW

**Comment by wy65701436** [comment]
@reasonerjt  How do I fix the failure? Add testing code?

**Comment by ywk253100** [comment]
Thank you for your contribution. You can add some UTs for package dao in dao/dao_test.go if you have enough time.

**Comment by wy65701436** [comment]
@ywk253100  got it, any other comments on code?

**Comment by ywk253100** [comment]
@wy65701436 The code is good to me.

**Pull request merged**
