### PR TITLE
Happy new year

### PR DESCRIPTION
**Pull request by tronicum**
you might do a 
s/Copyright (c) 2016 VMware, Inc. All Rights Reserved./opyright (c) 2017 VMware, Inc. All Rights Reserved./

### CODE REVIEW

**Comment by ywk253100** [comment]
@tronicum The PR is used for?

**Comment by tronicum** [comment]
Set copyright to include 2017

**Comment by reasonerjt** [comment]
@tronicum Thanks for the PR
However, I assume our legal team will provide new copy right headers for source files, so let me close it for now...

**Comment by tronicum** [comment]
i would advice tom remove the year from the file header something like "since 201x". 

the field i changed is the single file that is user facing in the UI.

**Comment by tronicum** [comment]
going to 2017 anytime soon?

**Comment by reasonerjt** [comment]
Not very soon, probably end of March

**Pull request closed without merging**
