### PR TITLE
Change LDAP Library and Improve LDAP Handling

### PR DESCRIPTION
**Pull request by rikatz**
This PR substitutes #1231 and is related to issue #1228 

It changes the LDAP library to go-ldap, and improves LDAP handling, mainly with configurable Dial Timeout.

Also this makes possible the evolution of Harbor with LDAP.

### CODE REVIEW

**Comment by rikatz** [comment]
@reasonerjt @yhua123 Again sorry for the mess.

**Comment by yhua123** [comment]
@rikatz:
Thanks for your hard work~~~
I have a suggestion:
I saw you help correct some typo and error for document, can you separate your PR to 2 parts, one for document update and one for update LDAP library?
The document PR can merge quickly.
Update LDAP PR, I will use your dev repo testing first and then merge to harbor dev. Maybe need sometime.
sorry for trouble your busy week :)

**Comment by rikatz** [comment]
@yhua123 No problems. Pretty busy this week here on the work, but will try to fix this at home!

**Comment by rikatz** [comment]
@yhua123 LGTM. 

About the license issue, don't think it's going to be a problem anymore, right?

About the docs, the thing is that I've run lint and gofmt against all the source code, and then all files where rewritten. Anyway, I can undo this, and do on separate commits (maybe separate branches).

What's the best approach to do this? Close this PR again and open other two?

Best rgds.

**Comment by yhua123** [comment]
@rikatz:
Yes, no license issue now. 
Better divide into two parts, thank you~

**Comment by rikatz** [comment]
@yhua123 Back from holydays. Will check this tomorrow, just to make this easier, may I:

1) close this PR
2) Create two new branches, one with the changes of LDAP Library and make PR for this one, and other to the Docs improvements?

Or is there another bether way to do this?

Thanks

**Comment by yhua123** [comment]
It's up to you. thanks~

**Comment by rikatz** [comment]
Closing this, and opening a new one, better organized :smile:

**Pull request closed without merging**
