### PR TITLE
set default value and on update option for timestamp column

### PR DESCRIPTION
**Pull request by ScorpioCPH**
also use all caps for mysql keywords.

### CODE REVIEW

**Comment by reasonerjt** [comment]
Thanks, for DB change please merge it to dev stream, could you also take a look at the db migration tool and help us make update to it?

**Comment by ScorpioCPH** [comment]
ok, i will try my best to do it :)

**Comment by ScorpioCPH** [comment]
send new PR to dev branch, close.

**Comment by ScorpioCPH** [comment]
@reasonerjt, is there any possible to re-send VMware CLA request, i use a invalid email, so i can't receive it, thanks.

**Comment by reasonerjt** [comment]
Maybe you could click the link in comments area of this PR?

**Comment by ScorpioCPH** [comment]
@reasonerjt, thanks, is there any discuss group for this project? such as WeChat or QQ?

**Comment by reasonerjt** [comment]
Yes there is, please email me your Wechat ID and I'll add you to the group

**Pull request closed without merging**
