### PR TITLE
add project role for non-sysadmin user

### PR DESCRIPTION
**Pull request by wemeya**

### CODE REVIEW

**Comment by ywk253100** [comment]
You can use function listRoles in api/utils.go.

**Comment by reasonerjt** [comment]
If this is an API I'd also wish to suggest adding a testcase

**Comment by reasonerjt** [comment]
If you look at the code, you don't need the IsAdmin code path...

**Comment by reasonerjt** [comment]
Also please add a test case for this particular API.

**Comment by wemeya** [comment]
I don't think call listRole is a better way to do this, though it judged whether a user is admin. In the List method, I need to judge whether the user is admin in advance, if yes, I just set the "projectList[i].Role = models.PROJECTADMIN", if not, I just need to query db to set the value. So I don't need the judgement again. I have talked about this with WenKai, you can have a whole look at the List method.

**Comment by reasonerjt** [comment]
@ywk253100 @wemeya let's accelerate this, it blocks some UI refinement work.

**Pull request merged**
