### PR TITLE
command line hash generator to help with update password hash

### PR DESCRIPTION
**Pull request by tronicum**
very simple hack to generate password hashes

### CODE REVIEW

**Comment by tronicum** [comment]
that 
```
tools/cli/newpasswdhash.go:6:9: cannot find package "crypto/pbkdf2" in any of:
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/crypto/pbkdf2 (from $GOROOT)
	/home/travis/gopath/src/crypto/pbkdf2 (from $GOPATH)
```
is odd as it is used in https://github.com/vmware/harbor/blob/master/src/common/utils/encrypt.go

**Comment by tronicum** [comment]
do you have a clue why it fails @yhua123 ?

**Comment by yhua123** [comment]
I am not finding obvious reason.
maybe coveralls service not stable, I pushed restart button and waiting for result.

**Comment by yhua123** [comment]
maybe you should add the pbkdf2 package to vendor/golang.org/x/crypto/pbkdf2
by default .tarvis environment don't have this package

**Comment by tronicum** [comment]
moving it below the src/ folder helped

**Comment by tronicum** [comment]
only needed to change old SHA passwords. obsolete with integration of #1422

**Comment by jcmartins** [comment]
My suggest is Blake2 it's very fast
https://godoc.org/golang.org/x/crypto/blake2b

See more details
https://research.kudelskisecurity.com/2017/03/06/why-replace-sha-1-with-blake2/

**Pull request closed without merging**
