### PR TITLE
Resize the defaultPageSize in api/base.go

### PR DESCRIPTION
**Pull request by KaleoCheng**
The defaultPageSize now could case the lack of initial replication if the project's repository is more than 10,So I resize it from 10 to 100.

### CODE REVIEW

**Comment by reasonerjt** [comment]
Sorry I don't think this is very necessary for code in master branch, you can update it in your deployment, but probably not to everyone?

**Comment by KaleoCheng** [comment]
Well,  and then how about add some tips in the documents? It  could make someone like me confused.

**Comment by reasonerjt** [comment]
yep, or maybe we'll consider to provide such configuration in cfg file, I'll keep this PR open until we provide such information in doc or conf.

**Comment by reasonerjt** [comment]
@KaleoCheng Sorry, could you elaborate in what scenario are you seeing this issue?  Are you feeling inconvenient using UI? or writing your own script?

**Comment by KaleoCheng** [comment]
Yeah, You could use the following steps to reproduce it:

1. create a new project;
2. push image to this project until it has more than 10 repositories;
3. make a replication for this project to another harbor;

the replication will be end when the another harbor gets 10 repositories.

**Comment by reasonerjt** [comment]
Ah I see this is a bug, let me open an issue, you can use this code change as a work around.

**Comment by KaleoCheng** [comment]
Fine,  then I'll close it for now.   Issue with #856

**Pull request closed without merging**
