### PR TITLE
add python3 compatibility to prepare file

### PR DESCRIPTION
**Pull request by saga92**
Let prepare file be compatible with python3.

### CODE REVIEW

**Comment by reasonerjt** [comment]
I see your organization is "VMware", are you employee in VMware?

**Comment by saga92** [comment]
Bro, I'm Bill He. Saga92 is my github account. @reasonerjt

**Comment by reasonerjt** [comment]
please sign the agreement, or re-create a PR, such that the Bot can be re-activated.

**Comment by saga92** [comment]
Done. @reasonerjt

**Pull request merged**
