### PR TITLE
Add ldap-search-password support to Helm Contrib 

### PR DESCRIPTION
**Pull request by ArcticSnowman**
New PR to replace #4619 - to clean up all the commits from the rebase.

### CODE REVIEW

**Comment by ArcticSnowman** [comment]
Pinging @jessehu and @paulczar

**Comment by ArcticSnowman** [comment]
What does `vmwclabot Pending — CLA is signed and under review, needs legal approval ` mean?

**Comment by jessehu** [comment]
Have you signed the CLA in other PR and got VMware legal approval?

**Comment by ArcticSnowman** [comment]
I signed the CLA and put in our legal rep to sign it off...  I believe he has done that..  Not seen any approval from VMWare..

**Pull request merged**
