### PR TITLE
update kubernetes deployment

### PR DESCRIPTION
**Pull request by kdada**

### CODE REVIEW

**Comment by kdada** [comment]
Please review the PR.
@reasonerjt  @hainingzhang @ywk253100  @ddysher

**Comment by kdada** [comment]
Thanks for your review. We will update it in the next few days.

@colemanserious

**Comment by colemanserious** [comment]
I've been working with these locally, and think I've found a bug + proposed fix.

Bug:  The docker pull command shown for a repository came up as /$project-name/$reponame:$version, rather than $hostname/$project-name/$reponame:$version.

Resolution:
Add the following to make/kubernetes/prepare:
`setconfig('ext_reg_url', get_config('hostname'))`

Add to make/kubernetes/templates/ui.cm.yaml:
`ext-reg-url: "{{ext_reg_url}"`

And to make/kubernetes/ui/ui.rc.yaml:
```
- name: EXT_REG_URL
  valueFrom: 
    configMapKeyRef:
      name: harbor-ui-config
      key: ext-reg-url
```

**Comment by kdada** [comment]
@colemanserious 
Thanks for your resolution.  
We update `make/kubernetes/templates/ui.cm.yaml` and `make/kubernetes/ui/ui.rc.yaml` .
`make/kubernetes/templates/ui.cm.yaml`:
```
# add field:
EXT_REG_URL: "{{hostname}}"
```
`make/kubernetes/ui/ui.rc.yaml`:
```
# add env EXT_REG_URL
- name: EXT_REG_URL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: EXT_REG_URL
```

You don't need to modify `make/kubernetes/prepare`. If you want to add some configs, you can add them to `harbor.cfg` and reference it in `*.cm.yaml` by `{{key_in_harbor_cfg}}`

**Pull request merged**
