### PR TITLE
Setup alternate non-interactive output formats for install.sh, minor install doc edits

### PR DESCRIPTION
**Pull request by lwh**
In automated builds without interactivity tput doesn't work.

### CODE REVIEW

**Comment by yhua123** [comment]
I try to running new install script after setting interactive mode.
$set -i
$echo "$-"
himBH
$./install
...
----Harbor has been installed and started successfully.----

expect shown:
✔ ----Harbor has been installed and started successfully.----

do you know the reason? thanks

my system os:
Ubuntu 14.04

**Comment by lwh** [comment]
I couldn't see what it was, assumed it was color codes, I put them back in.

**Comment by reasonerjt** [comment]
@yhua123 please double check regarding this PR should be merged to master or dev.

**Comment by yhua123** [comment]
@lwh,
Sorry, maybe didn't make myself clear.
I mean when I setting the interactive mode(set -i), the shell still go into "*)" branch. do you know the reason? Thanks~

**Comment by yhua123** [comment]
@lwh 
I will help you fix this issue. close this pr first.
I will open an issue and fix this shell later.
Thanks~

**Pull request closed without merging**
