### PR TITLE
Harbor增加客户镜像过滤功能

### PR DESCRIPTION
**Pull request by MarkThink**
新增三张数据表，具体可以参看视频介绍!

- 新增镜像分页、客户镜像过滤功能
- 新增客户数据统计
- 增加树状客户过滤
- 新增镜像标签功能
- 增加项目中文显示

录制的视频地址: https://pan.baidu.com/s/1pKHWhbt

### CODE REVIEW

**Comment by bobbyjunzhang** [comment]
@MarkThink 视频太好了！！新的功能也貌似很棒（还没仔细看）！谢谢！！

**Comment by bobbyjunzhang** [comment]
@MarkThink CI好像没过，请看下。

**Comment by reasonerjt** [comment]
@MarkThink Thanks, but it's such big change, seems different features involved, maybe we'll first look at the video and later decide which will be merged?
Also please remove Chinese from the code, except the Chinese message in the message file for UI.

**Comment by MarkThink** [comment]
@bobbyjunzhang CI看了一下，我注意到单元测试没有通过..谢谢！

**Pull request closed without merging**
