### PR TITLE
Feature/accesslog

### PR DESCRIPTION
**Pull request by hmwenchen**
Add tag info access log. The tag info can been seen by clicking "Logs" tab on project detail page.

### CODE REVIEW

**Comment by ywk253100** [comment]
@hmwenchen Some codes in you pull request do not meet the requirements, please notes the results of CI.

**Comment by ywk253100** [comment]
As far as I know, registry 2.4 supports "tag" field in the events sent by registry, you can use it to implement this feature.

**Comment by hmwenchen** [comment]
The PullManifest function in utils retrieve schemeVersion2 Manifest, which contains no tag info. According to docker registry API, tag info is included in schemeVersion1. 
However, currently PullManifest funtion does not support scheme1, as the Header is an empty map and the line "req.Header.Set(http.CanonicalHeaderKey("Accept"), version.MediaType)" has no effect. Perhaps it is a bug? Should it change to req.Header.Add() ?

I would like to know how to retrieve scheme1 manifest result. 

Thank you!

**Comment by hmwenchen** [comment]
@ywk253100 Neither can I obtain tag info from registry. The "docker push/pull"  send out event which contains a target of scheme2 mediaType. And GET request to scheme2 manifest retrieves no tag info.

**Comment by ywk253100** [comment]
Are you using the registry 2.4? Harbor is using registry 2.3 now, but we will upgrade to 2.4. So you can implement and test this feature in 2.4.

When you pull from or push to the registry 2.4, no matter schema 1 or schema 2, the events sent from registry to your endpoints will contain the "tag" field as below:
```
"target": {
            "mediaType": "application/vnd.docker.distribution.manifest.v1+prettyjws",
            "size": 2749,
            "digest": "sha256:bb39087fb4d12a5d9f2d179759a8599fa943cdc1922e1088215be5cd838b6858",
            "length": 2749,
            "repository": "test/hello-world",
            "url": "http://10.117.171.217:5005/v2/test/hello-world/manifests/sha256:bb39087fb4d12a5d9f2d179759a8599fa943cdc1922e1088215be5cd838b6858",
            "tag": "latest"
         }
```

```
"target": {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 708,
            "digest": "sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf",
            "length": 708,
            "repository": "hello-world",
            "url": "http://10.117.171.217:5005/v2/hello-world/manifests/sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf",
            "tag": "latest"
         }
```

**Comment by hmwenchen** [comment]
@ywk253100 So how shall I upgrade to registry 2.4? 
I changed the registry to 2.4.0 in docker-compose.yml, and then got 404 error at "docker login". Besides, the harbor UI cannot be visited through browser.

**Comment by hmwenchen** [comment]
@ywk253100 The error message in docker_registry.log looks like: 
Error: unknown command "/etc/registry/config.yml"

The error message in docker_proxy.log looks like:

Apr 25 21:18:22 jessyz-virtual-machine docker/proxy[998]: 2016/04/25 13:18:22 [error] 8#8: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.189.3, server: , request: "GET /v2/ HTTP/1.1", upstream: "http://180.168.41.175:5000/v2/", host: "192.168.189.3"
Apr 25 21:18:22 jessyz-virtual-machine docker/proxy[998]: 192.168.189.3 - - [25/Apr/2016:13:18:22 +0000] "GET /v2/ HTTP/1.1" 502 173 "-" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.19.0-56-generic os/linux arch/amd64"
Apr 25 21:18:22 jessyz-virtual-machine docker/proxy[998]: 192.168.189.3 - - [25/Apr/2016:13:18:22 +0000] "GET /v1/_ping HTTP/1.1" 404 169 "-" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.19.0-56-generic os/linux arch/amd64"
Apr 25 21:18:22 jessyz-virtual-machine docker/proxy[998]: 192.168.189.3 - - [25/Apr/2016:13:18:22 +0000] "POST /v1/users/ HTTP/1.1" 404 169 "-" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.19.0-56-generic os/linux arch/amd64"

**Comment by ywk253100** [comment]
You should modify "image" and "command" fields in docker-compose.yml as below:
```
  registry:
    image: registry:2.4
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    ports:
      - 5001:5001
    command:
      serve /etc/registry/config.yml
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "registry"
```

**Comment by hmwenchen** [comment]
@ywk253100  Thanks! However, I ran into another problem at "docker login":

root@jessyz-virtual-machine:/home/jessyz/workspace/harbor/Deploy# docker login 192.168.189.3
Username (hmwenchen): hmwenchen
Password:
Error response from daemon: no successful auth challenge for http://192.168.189.3/v2/ - errors: [Get http://$ui_url/service/token?account=hmwenchen&service=token-service: dial tcp: lookup $ui_url: invalid domain name]

In harbor.cfg, I have already set the hostname to my IP.

**Comment by ywk253100** [comment]
The variable "ui_url" will be replaced by its real value configured in harbor.cfg after running prepare script. So you can run prepare again and check if the "ui_url" is modified correctly. You can find the variable in harbor/Deploy/config/registry/config.yml.

**Comment by hmwenchen** [comment]
@ywk253100 I can docker login and docker pull now, and got tag info from event. However, I cannot access harbor UI, and docker_registry.log says: 

error writing events: httpSink{http://ui/service/notifications}: error posting: Post http://ui/service/notifications: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying"

Is it due to "ui" in config.yml?

**Comment by hmwenchen** [comment]
Still the error if replacing "ui" with IP: 

"retryingsink: error writing events: httpSink{http://192.168.189.3/service/notifications}: error posting: Post http://192.168.189.3/service/notifications: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying

**Comment by hmwenchen** [comment]
It seems too many events are sent after "docker pull/push". 

Error in docker_ui.log:

Apr 26 20:47:05 jessyz-virtual-machine docker/ui[1077]: message repeated 14 times: [ 2016-04-26T12:47:05Z [ERROR] [accesslog.go:108]: error in AccessLog: Error 1213: Deadlock found when trying to get lock; try restarting transaction ]

**Comment by ywk253100** [comment]
The "ui" field is right in config.yml. The timeout error is not caused by it. Could you enter the registry container and copy the result of command "ping ui" and the content of /etc/resolv.conf here?

**Comment by hmwenchen** [comment]
root@c6d9cba3ee09:/# ping ui
PING ui (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: icmp_seq=0 ttl=64 time=1.164 ms
64 bytes from 172.18.0.4: icmp_seq=1 ttl=64 time=0.156 ms

root@c6d9cba3ee09:/# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

**Comment by hmwenchen** [comment]
@ywk253100
It seems too many events are sent after "docker pull/push".
Error in docker_ui.log:
Apr 26 20:47:05 jessyz-virtual-machine docker/ui[1077]: message repeated 14 times: [ 2016-04-26T12:47:05Z [ERROR] [accesslog.go:108]: error in AccessLog: Error 1213: Deadlock found when trying to get lock; try restarting transaction ]

Previously, as I debug the notification event with registry 2.3, there is no such error as deadlock and too many events. Is it due to the upgrade to registry 2.4 ?

**Comment by ywk253100** [comment]
@hmwenchen The two problems seem to be caused by the same reason: the timeout in registry is too short. We have modified it and you can pull the latest codes and re-build Harbor.

**Comment by hmwenchen** [comment]
hostname = 192.168.189.3

ui_url_protocol = http

#Email account settings for sending out password resetting emails.
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

##The password of Harbor admin, change this before any production use.
harbor_admin_password= Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#The basedn template to look up a user in LDAP and verify the user's password.
ldap_basedn = uid=%s,ou=people,dc=mydomain,dc=com

#The password for the root user of mysql db, change this before any production use.
db_password = 123456

self_registration = on
#####

#Turn on or off the customize your certicate
customize_crt = on

#fill in your certicate message
crt_country = CN
crt_state = State
crt_location = CN
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = example.com
crt_email = example@example.com

**Comment by ywk253100** [comment]
LGTM

**Pull request merged**
