### PR TITLE
add ssl support for send email

### PR DESCRIPTION
**Pull request by xionglun**
Some mail service providers use ssl connection to send/receive emails.
Had test with tencent's enterprise mail success: **smtp.exmail.qq.com:465**

### CODE REVIEW

**Comment by reasonerjt** [comment]
@xionglun What error does this PR try to fix?

**Comment by xionglun** [comment]
@reasonerjt 
image

Currently, code didn't support **SSL** connection!
Mail providers such as [QQ Exmail](https://exmail.qq.com/) don't support non-ssl smtp email send.

This PR try to add **SSL support** for emails.

**Comment by reasonerjt** [comment]
https://golang.org/src/net/smtp/smtp.go#L300

godoc says smtp pkg supports TLS by default, we'll do more testing before make decision on this PR.
Could you let us know what error did you see and you have to make the change to fix it?

**Comment by xionglun** [comment]
Golang's [implementation](https://github.com/golang/go/blob/master/src/net/smtp/smtp.go#L146)  does not use TLS by default, it will upgrade an existing insecure connection to a secure connection if server support.

And you can read **SendMail**'s [comment](https://github.com/golang/go/blob/master/src/net/smtp/smtp.go#L280)
> // SendMail connects to the server at addr, switches to TLS if
> // possible, authenticates with the optional mechanism a if possible,
> // and then sends an email from address from, to addresses to, with
> // message msg.

I think the problem is that: 
Some mail providers don't support insecure connection at all.
So you can't start off as plaintext, then upgrade the connection to an SSL/TLS encrypted one.



Additional Doc:
[SSL vs TLS vs STARTTLS](https://www.fastmail.com/help/technical/ssltlsstarttls.html)

**Comment by reasonerjt** [comment]
@xionglun Thanks I see your point.  Seems smtp package should provide more api...
But as long as this fixes your problem, could you please update the default value of email_ssl to false and add more explanation of this attribute in the .md file?

**Comment by xionglun** [comment]
@reasonerjt  I have squashed my commit, and set email_ssl to false by default.

**Pull request merged**
