### PR TITLE
ISSUE-3460 - Fix link to Notary repo

### PR DESCRIPTION
**Pull request by Evalle**
See https://github.com/vmware/harbor/issues/3460 for more info

### CODE REVIEW

**Comment by Evalle** [comment]
Not sure why continuous-integration/vic/pr is failing, could someone take a look at it?

**Comment by wy65701436** [comment]
Thanks for the PR.

**Comment by wy65701436** [comment]
@Evalle , this PR LGTM, could you please reword the commit message? It's because that we have a message convention which should be a imperative sentence.

**Comment by wy65701436** [comment]
@reasonerjt, do we need to update the vendor README?

**Comment by wy65701436** [comment]
@Evalle , could your remove the change for README.md? This shouldn't be changed.
I will merge the PR if it done.

**Comment by Evalle** [comment]
@wy65701436 sure I can. thank you for the review btw :)

**Comment by wy65701436** [comment]
@Evalle coud you please help to sync with latest code and commit again? The CI has a limitation when the .drone.yml is changed, it cannot sync with the latest but manually.

No PR can be merged if the CI fail.

**Comment by Evalle** [comment]
@wy65701436 Sure, it's already done

**Pull request merged**
