### PR TITLE
fix swagger yaml comment

### PR DESCRIPTION
**Pull request by andyxning**
Fix swagger configuration comment. :)

### CODE REVIEW

**Comment by reasonerjt** [comment]
Thanks, but this has been fixed in dev branch, we'll merge dev branch into master very soon, so I'm closing this PR.

**Comment by andyxning** [comment]
@reasonerjt Maybe we need to make it clear by writing that all PRs will be pointed to the `dev` branch in readme. :)

**Comment by wy65701436** [comment]
thanks @andyxning, in the next release we will use master as the main branch, no dev branch anymore. And any PR can be pointed to master.

**Comment by andyxning** [comment]
@wy65701436 👏

**Pull request closed without merging**
