### PR TITLE
Add ldap-search-password support to Helm Contrib

### PR DESCRIPTION
**Pull request by ArcticSnowman**
Added field to values.yaml and updated the adminserver.cm.yaml to add support for search password.
(aka BindPassword)

### CODE REVIEW

**Comment by jessehu** [comment]
@ArcticSnowman please sign the CLA per github notice. Then we can merge your PR.

**Comment by ArcticSnowman** [comment]
Waiting for company legal approval....

**Comment by draeron** [comment]
i'd just like to mention, k8s best pratices state that passwords should be stored in secrets, not in config map. 

**adminserver-secrets.yaml **
```yaml
{{- if eq .Values.adminserver.authenticationMode "ldap_auth" }} 
  LDAP_SEARCH_PWD: {{ .Values.adminserver.ldap.searchPwd | b64enc | quote }} 
{{- end }} 
```

**Comment by jessehu** [comment]
@draeron Good point. I will make the change.

**Comment by jessehu** [comment]
@ArcticSnowman I didn't realize this PR is not merged yet. Maybe I forget to merge. Could you please improve it by adding the lines for "LDAP_SEARCH_PWD: {{ .Values.adminserver.ldap.searchPwd | b64enc | quote }}" into adminserver-secrets.yaml ?

**Comment by ArcticSnowman** [comment]
Updates... also remove the Clair DB password from the CM as it's already in the Secrets file.

**Comment by jessehu** [comment]
@ArcticSnowman there should be rebase problem which causes you to push 109 commits :)

**Comment by ArcticSnowman** [comment]
Yeah, I did a rebase to catch up to master...

**Comment by ArcticSnowman** [comment]
Closing and making a new one to clean up the rebase commits.

**Pull request closed without merging**
