### PR TITLE
Add sqlite support

### PR DESCRIPTION
**Pull request by ywk253100**

### CODE REVIEW

**Comment by reasonerjt** [comment]
is it possible to use one sql script to both mysql and sqllite?

**Comment by ywk253100** [comment]
The keywords for auto increment in MySQL and SQLite are different. So it could be difficult to share the same sql script.

**Comment by reasonerjt** [comment]
Closing it for now, just to avoid merge my mistake.

**Comment by reasonerjt** [comment]
Too busy this week, let's go through this after Oct. 10 :)

**Pull request merged**
