### PR TITLE
[DOC] Added docker-compose modification for https to work

### PR DESCRIPTION
**Pull request by acaranta**
Hi !

Just a tiny bit of documentation add, to notify users to add the 443 port to the compose file when configuring https on harbor.

Thanks !

### CODE REVIEW

**Comment by acaranta** [comment]
done ...

**Comment by reasonerjt** [comment]
@acaranta Thanks for your help!  However, the PR #102 has been merged to expose 443 port in compose template, so it's no longer needed to update the compose template.

**Comment by acaranta** [comment]
right sorry, did not see that PR ... :/

(However, I wonder if it is really necessary to export port 443 if https is not configured...)

I'll close this PR nevertheless ;)

**Comment by reasonerjt** [comment]
Thanks, @acaranta

**Pull request closed without merging**
