### PR TITLE
label volumes for SELinux

### PR DESCRIPTION
**Pull request by knackaron**
allow Harbor to run when dockerd is running with --selinux-enabled

example AVC denials:
type=AVC msg=audit(1488384855.681:154671): avc:  denied  { read } for  pid=454 comm="registry" name="config.yml" dev="dm-8" ino=12583048 scontext=system_u:system_r:svirt_lxc_net_t:s0:c298,c958 tcontext=system_u:object_r:default_t:s0 tclass=file
type=AVC msg=audit(1488384855.681:154671): avc:  denied  { open } for  pid=454 comm="registry" path="/etc/registry/config.yml" dev="dm-8" ino=12583048 scontext=system_u:system_r:svirt_lxc_net_t:s0:c298,c958 tcontext=system_u:object_r:default_t:s0 tclass=file
type=AVC msg=audit(1488384855.687:154672): avc:  denied  { append } for  pid=350 comm=72733A6D61696E20513A526567 name="registry.log" dev="dm-5" ino=4315920 scontext=system_u:system_r:svirt_lxc_net_t:s0:c599,c800 tcontext=system_u:object_r:default_t:s0 tclass=file
type=AVC msg=audit(1488384856.895:154702): avc:  denied  { remove_name } for  pid=708 comm="mysqld" name="4691d4d62464.lower-test" dev="dm-12" ino=402656159 scontext=system_u:system_r:svirt_lxc_net_t:s0:c149,c797 tcontext=system_u:object_r:default_t:s0 tclass=dir
type=AVC msg=audit(1488384856.926:154703): avc:  denied  { lock } for  pid=708 comm="mysqld" path="/var/lib/mysql/ibdata1" dev="dm-12" ino=402656097 scontext=system_u:system_r:svirt_lxc_net_t:s0:c149,c797 tcontext=system_u:object_r:default_t:s0 tclass=file
type=AVC msg=audit(1488384857.958:154736): avc:  denied  { open } for  pid=924 comm="harbor_jobservi" path="/etc/jobservice/app.conf" dev="dm-8" ino=142 scontext=system_u:system_r:svirt_lxc_net_t:s0:c102,c158 tcontext=system_u:object_r:default_t:s0 tclass=file
type=AVC msg=audit(1488384858.089:154737): avc:  denied  { read } for  pid=1017 comm="nginx" name="nginx.conf" dev="dm-8" ino=4194445 scontext=system_u:system_r:svirt_lxc_net_t:s0:c847,c996 tcontext=system_u:object_r:default_t:s0 tclass=file
type=AVC msg=audit(1488384858.089:154737): avc:  denied  { open } for  pid=1017 comm="nginx" path="/etc/nginx/nginx.conf" dev="dm-8" ino=4194445 scontext=system_u:system_r:svirt_lxc_net_t:s0:c847,c996 tcontext=system_u:object_r:default_t:s0 tclass=file

reference: http://www.projectatomic.io/blog/2016/07/docker-selinux-flag/

### CODE REVIEW

**Comment by reasonerjt** [comment]
@knackaron Thanks for the PR!
What do you think if the label for all volumes are set to ":z" (lower case), so they can be shared between containers, for example a configuration container may try to manipulate the config.yml.

**Comment by knackaron** [comment]
@reasonerjt Is a configuration container the route that Harbor is going in the future?  If not, I don't think defaulting to a less secure implementation is the right choice.  Registry security is a critical component in ensuring a secure Docker architecture and shouldn't be treated lightly.  However, if the recommended deployment scenario is for Harbor to be deployed in a standalone VM (a good idea in the first place and how I deploy it for our customers), running with shared volumes doesn't weaken the security of the deployment.

**Comment by reasonerjt** [comment]
It is in dev branch, so how about this, let it be ":Z" uppercase by default, and when needed, we'll update the option to ":z".

But I have limited knowledge in selinux, and on my VM I have --selinux-enabled in the parm of dockerd, and Harbor can be deployed without your option.  Do I have to create the file 
``` /etc/selinux/targeted/contexts/lxc_contexts``` as in the blog you attach to reproduce the problem?

**Comment by reasonerjt** [comment]
@knackaron yes please make the update.

And as for my env:
OS: Ubuntu:trusty
docker: 1.12.3

**Pull request merged**
