### PR TITLE
Add documentation to run Harbor using Docker Machine.

### PR DESCRIPTION
**Pull request by AlexZeitler**

### CODE REVIEW

**Comment by reasonerjt** [comment]
@AlexZeitler Thanks for the PR!
We plan to create a contrib directory to contain the stuff contributed by community.  
Could you put this doc in another md and put it to that directory?

**Comment by AlexZeitler** [comment]
Ok. Should I create /contrib/deployingharborwithdockermachine.md or /docs/contrib/...md or /contrib/docs/...md ?

**Comment by reasonerjt** [comment]
I merged my change to add contrib directory.
For now, please sync your fork then put it under /contrib/ folder, such as /contrib/deploy_dockermachine.md
When there are more stuff we can move it around in /contrib/ directory as needed.

**Comment by AlexZeitler** [comment]
Done.

**Pull request merged**
